input:
    aws_s3:
        region: "eu-north-1"
        credentials:
            id: "<YOUR-AWS-ACCESS-ID>"
            secret: "<YOUR-AWS-SECRET>"
            from_ec2_role: false
        sqs:
            url: "https://sqs.<YOUR-AWS-REGION>.amazonaws.com/<YOUR-AWS-ACCOUNT-ID>/<YOUR-SQS-QUEUE-NAME>"
            key_path: Records.*.s3.object.key
            bucket_path: Records.*.s3.bucket.name

pipeline:
    processors:
        - branch:
              processors:
                  - openai_chat_completion:
                        api_key: "<YOUR-OPENAI-SECRET-KEY>"
                        model: gpt-4o-mini
                        prompt: "Provide a descriptive caption for this image"
                        image: "root = content()"
              result_map: |
                  root.caption = content().string()
        - branch:
              processors:
                  - openai_embeddings:
                        api_key: "<YOUR-OPENAI-SECRET-KEY>"
                        model: text-embedding-3-small
                        text_mapping: this.caption
              result_map: |
                  root.embeddings = this
        - mapping: |
              root = this
              root.image_url = "https://<YOUR-AWS-BUCKET>.s3.<YOUR-AWS-REGION>.amazonaws.com/" + meta("s3_key")

output:
    sql_raw:
        driver: postgres
        dsn: postgres://<YOUR-DB-USERNAME>:<YOUR-DB-PASSWORD>@<YOUR-DB-HOST>:5432/<YOUR-DB-NAME>?sslmode=disable
        query: UPDATE products SET description = $1, embedding = $2 WHERE image_url = $3;
        args_mapping: root = [this.caption, this.embeddings.vector(), this.image_url]
